### ISSUE TITLE
403 for everything

### ISSUE THREAD

**Issue by Nekromateion** [pypy-vrc/VRCX#171]
It seems like VRChat now returns a 403 whenever you send a request without a valid User-Agent.

**Comment by Murkur** [comment]
vrchat now requires certian api headers to be sent

**Comment by Murkur** [comment]
its currently being fixed by some contributors here 👍

**Comment by Natsumi-sama** [comment]
👌 https://github.com/pypy-vrc/VRCX/commit/0e326faecc8fb80ce72397b5aaaf2a1f0133d4d9

**Comment by xAstroBoy** [comment]
I Compiled it and it does give me a white form, nothing else.

**Comment by Murkur** [comment]
> I Compiled it and it does give me a white form, nothing else.

because you didnt copy the HTML folder to the build location

**Comment by untuned** [comment]
Built it *correctly*, and it still shows a 403. I am not sure what's happening.

**Comment by Natsumi-sama** [comment]
Need to pull the latest source code down.

**Comment by untuned** [comment]
> Need to pull the latest source code down.

That's what I did when I started getting the 403 messages.

**Comment by Miner28** [comment]
Just tried pulling it and building too and also gives 403

**Comment by xAstroBoy** [comment]
Yup, still giving 403 messages.

**Comment by Natsumi-sama** [comment]
I tried a fresh build and yea it's still doing 403 errors, give me a bit to figure it out.

**Comment by AdmiralTeitoku** [comment]
> > I Compiled it and it does give me a white form, nothing else.
> 
> because you didnt copy the HTML folder to the build location

Really new to this kind of stuff. Where is the build location?

**Comment by Miner28** [comment]
Check the very bottom of the Readme it might help you with what all you need to do :)

**Comment by Natsumi-sama** [comment]
Okay this should do it, was caused the header containing the user agent being overwritten, so it would only work if you were already logged in. https://github.com/pypy-vrc/VRCX/commit/eb8e1a7e7f5bea332774819ff9cc7869a06b8e49

**Comment by untuned** [comment]
> Okay this should do it, was caused the header containing the user agent being overwritten, so it would only work if you were already logged in. [eb8e1a7](https://github.com/pypy-vrc/VRCX/commit/eb8e1a7e7f5bea332774819ff9cc7869a06b8e49)

That fixed it! If anyone wants a download to use **until the next official release**, I have uploaded it to my Google Drive. You may download it by [clicking here](https://drive.google.com/file/d/1Glt4gfrfsWaxkYSbqin_J9EZe6Wvqujt/view?usp=sharing). It is unmodified from source.

**Comment by Natsumi-sama** [comment]
Idk what you have done there chief but a lot of extra dlls going on, I would much prefer people to use my fork in the mean time https://github.com/Natsumi-sama/VRCX/releases/tag/v2021.04.04

**Comment by Natsumi-sama** [comment]
New release https://github.com/pypy-vrc/VRCX/releases/tag/v2021.04.04

**Comment by Kieaer** [comment]
I think it's solved.

**Comment by Murkur** [comment]
it has been @Natsumi-sama might wanna mark this as solved

**Comment by Natsumi-sama** [comment]
Was leaving it open so that people could see why they needed to update.
