### ISSUE TITLE
Two notifications when a person leaves the instance

### ISSUE THREAD

**Issue by wststreet2** [pypy-vrc/VRCX#300]
I often get this "Unnamed won't, disabled has left" message after someone leaves. That "Unnamed" isn't a real person, I never see a join, just a leave notification. It only happens to me in this world (Infinite Night).
I think I've seen it show just "Unnamed" once.

![image](https://user-images.githubusercontent.com/2018602/148385561-aa60728d-f55f-413e-8844-a42c867c75d6.png)
![image](https://user-images.githubusercontent.com/2018602/148385890-880f0a7b-5fdf-4eb9-8574-b0fc5353f406.png)

VRCX Version: 2021.12.16

**Comment by Natsumi-sama** [comment]
Fixed here https://github.com/pypy-vrc/VRCX/commit/6c8907727691179c66c0373d329e78e4b245d785

**Comment by Williampurple** [comment]
how to install it?

**Comment by slord399** [comment]
https://github.com/pypy-vrc/VRCX/releases
or
Do "Check for update" from settings.

**Comment by wststreet2** [comment]
Still happening with the latest release.
![image](https://user-images.githubusercontent.com/2018602/152382440-a20f9bbb-30ec-40a7-a453-74abc1701f09.png)
![image](https://user-images.githubusercontent.com/2018602/152382480-160e3caf-4451-4965-8f8b-34963c5ce041.png)

**Comment by Natsumi-sama** [comment]
I can't replicate this can you send me the line from your VRChat log file that contains "Unnamed won't"

**Comment by wststreet2** [comment]
```
022.02.05 21:23:32 Log        -  [Behaviour] Custom:StartTest won't, disabled
2022.02.05 21:23:33 Log        -  [Behaviour] Will execute ActivateCustomTrigger/AlwaysUnbuffered on Master Local - Master Trigger (UnityEngine.GameObject) for Castiello: S: "StartTest" I: 0 F: 0 B: False (non-local non-master non-owner)
2022.02.05 21:23:33 Log        -  [Behaviour] Custom:StartTest won't, disabled
2022.02.05 21:23:33 Log        -  [Behaviour] uSpeak [4][-1436611946](every 10): voice buffer underrun, sample arrived 3ms late
2022.02.05 21:23:34 Log        -  [Behaviour] Will execute ActivateCustomTrigger/AlwaysUnbuffered on Master Local - Master Trigger (UnityEngine.GameObject) for Potbottom: S: "StartTest" I: 0 F: 0 B: False (non-local non-master non-owner)
2022.02.05 21:23:34 Log        -  [Behaviour] Custom:StartTest won't, disabled
2022.02.05 21:23:34 Log        -  [Behaviour] OnPlayerLeftRoom
2022.02.05 21:23:34 Log        -  [Behaviour] Cleaning up held messages
2022.02.05 21:23:34 Log        -  [Network Processing] Transferred ownership of VRCPlayer[Remote] 61671581 7 to Street｜Train.
2022.02.05 21:23:34 Log        -  [Network Processing] Transferred ownership of USpeak to Street｜Train.
2022.02.05 21:23:34 Log        -  [Network Processing] Transferred ownership of PlayableController to Street｜Train.
2022.02.05 21:23:34 Log        -  [Network Processing] Transferred ownership of BigData to Street｜Train.
2022.02.05 21:23:34 Log        -  [Behaviour] OnPlayerLeft Nixfinity
2022.02.05 21:23:34 Log        -  [Behaviour] OnPlayerLeft:Unnamed won't, disabled
2022.02.05 21:23:34 Log        -  [Behaviour] Removed player Nixfinity
2022.02.05 21:23:34 Log        -  [Behaviour] Unregistering Nixfinity
2022.02.05 21:23:34 Exception  -  Object reference not set to an instance of an object.
  at ǅǅǅǄǄǄǅǄǄǄǅǄǅǅǅǄǄǅǄǅǄǄǄǅǄǅǄǅǅǄǄǅǅǄǄǄǅǅǄǄǅǄǄǄǄǄǄ.ǄǄǄǄǄǄǅǄǅǄǅǅǄǅǅǄǄǄǄǅǅǄǄǅǄǄǄǅǄǅǄǅǄǄǅǄǄǅǄǄǅǅǄǄǄǅǅ () [0x00000] in <00000000000000000000000000000000>:0 
  at ǅǄǄǅǅǄǅǄǄǅǅǄǄǅǅǄǅǄǄǄǅǅǄǄǄǅǅǅǄǄǅǅǅǅǅǅǅǄǄǅǅǅǄǄǅǅǅ.Invoke () [0x00000] in <00000000000000000000000000000000>:0 
  at ǅǄǄǅǅǄǅǄǄǅǅǄǄǅǅǄǅǄǄǄǅǅǄǄǄǅǅǅǄǄǅǅǅǅǅǅǅǄǄǅǅǅǄǄǅǅǅ.Invoke () [0x00000] in <00000000000000000000000000000000>:0 
  at ǅǄǄǄǄǄǅǅǄǅǅǄǅǄǅǄǄǄǄǄǅǄǄǄǄǅǄǅǄǄǄǅǄǅǄǅǅǅǅǄǄǄǅǄǅǄǄ.ǄǅǅǅǅǄǄǄǅǄǅǄǄǅǅǄǄǄǄǄǄǄǄǄǄǄǅǅǅǄǅǅǄǅǄǅǅǄǄǄǅǅǅǅǄǅǅ () [0x00000] in <00000000000000000000000000000000>:0 
  at ǅǅǄǅǄǄǅǄǅǄǅǄǄǅǄǅǄǅǄǅǄǅǄǄǄǅǄǄǄǄǅǅǅǅǄǅǅǄǅǅǄǅǅǄǄǅǄ.ǄǅǅǄǅǅǄǄǄǅǅǅǄǄǅǅǄǄǄǄǅǄǄǄǅǅǄǄǅǄǅǄǄǄǅǄǅǄǄǄǅǄǄǄǄǄǅ () [0x00000] in <00000000000000000000000000000000>:0 
2022.02.05 21:23:35 Log        -  [Behaviour] uSpeak [1][-1436609674](every 30): USpeakOnSerializeAudio packet sent via photon: { 2,3,4,5,6,8,9, }, 119 bytes
2022.02.05 21:23:36 Log        -  [Behaviour] Will execute ActivateCustomTrigger/AlwaysUnbuffered on Master Local - Master Trigger (UnityEngine.GameObject) for Castiello: S: "StartTest" I: 0 F: 0 B: False (non-local non-master non-owner)
2022.02.05 21:23:36 Log        -  [Behaviour] Custom:StartTest won't, disabled
2022.02.05 21:23:36 Log        -  [Behaviour] Will execute ActivateCustomTrigger/AlwaysUnbuffered on Master Local - Master Trigger (UnityEngine.GameObject) for Largo: S: "StartTest" I: 0 F: 0 B: False (non-local non-master non-owner)
2022.02.05 21:23:36 Log        -  [Behaviour] Custom:StartTest won't, disabled
2022.02.05 21:23:36 Log        -  [Behaviour] Will execute ActivateCustomTrigger/AlwaysUnbuffered on Master Local - Master Trigger (UnityEngine.GameObject) for d v l: S: "StartTest" I: 0 F: 0 B: False (non-local non-master non-owner)
2022.02.05 21:23:36 Log        -  [Behaviour] Custom:StartTest won't, disabled
2022.02.05 21:23:36 Log        -  [Behaviour] Will execute ActivateCustomTrigger/AlwaysUnbuffered on Master Local - Master Trigger (UnityEngine.GameObject) for kaylen17: S: "StartTest" I: 0 F: 0 B: False (non-local non-master non-owner)
2022.02.05 21:23:36 Log        -  [Behaviour] Custom:StartTest won't, disabled
2022.02.05 21:23:36 Log        -  [Behaviour] Will execute ActivateCustomTrigger/AlwaysUnbuffered on Master Local - Master Trigger (UnityEngine.GameObject) for Potbottom: S: "StartTest" I: 0 F: 0 B: False (non-local non-master non-owner)
2022.02.05 21:23:36 Log        -  [Behaviour] Custom:StartTest won't, disabled
2022.02.05 21:23:36 Log        -  [Behaviour] Will execute SendRPC/AlwaysUnbuffered on USpeak (UnityEngine.GameObject) for d v l: S: "ReceiveVoiceStatsSyncRPC" I: 9 F: 0 B: 255 (non-local non-master owner)
2022.02.05 21:23:36 Log        -  [Behaviour] Will execute SendRPC/AlwaysUnbuffered on USpeak (UnityEngine.GameObject) for d v l: S: "ReceiveVoiceStatsSyncRPC" I: 9 F: 0 B: 255 (non-local non-master owner)
2022.02.05 21:23:36 Log        -  [Behaviour] Will execute SendRPC/AlwaysUnbuffered on USpeak (UnityEngine.GameObject) for d v l: S: "ReceiveVoiceStatsSyncRPC" I: 9 F: 0 B: 255 (non-local non-master owner)
2022.02.05 21:23:36 Log        -  [Behaviour] Will execute SendRPC/AlwaysUnbuffered on USpeak (UnityEngine.GameObject) for d v l: S: "ReceiveVoiceStatsSyncRPC" I: 9 F: 0 B: 255 (non-local non-master owner)
2022.02.05 21:23:36 Log        -  [Behaviour] Will execute SendRPC/AlwaysUnbuffered on USpeak (UnityEngine.GameObject) for d v l: S: "ReceiveVoiceStatsSyncRPC" I: 9 F: 0 B: 255 (non-local non-master owner)
2022.02.05 21:23:36 Log        -  [Behaviour] Will execute SendRPC/AlwaysUnbuffered on USpeak (UnityEngine.GameObject) for d v l: S: "ReceiveVoiceStatsSyncRPC" I: 9 F: 0 B: 255 (non-local non-master owner)
2022.02.05 21:23:36 Log        -  [Behaviour] Will execute SendRPC/AlwaysUnbuffered on USpeak (UnityEngine.GameObject) for d v l: S: "ReceiveVoiceStatsSyncRPC" I: 9 F: 0 B: 255 (non-local non-master owner)
2022.02.05 21:23:37 Log        -  [Behaviour] Will execute ActivateCustomTrigger/AlwaysUnbuffered on Master Local - Master Trigger (UnityEngine.GameObject) for d v l: S: "StartTest" I: 0 F: 0 B: False (non-local non-master non-owner)
2022.02.05 21:23:37 Log        -  [Behaviour] Custom:StartTest won't, disabled
2022.02.05 21:23:37 Log        -  [API] Received Message of type: friend-update received at 02/05/2022 19:23:37 UTC
2022.02.05 21:23:37 Log        -  [Behaviour] Will execute ActivateCustomTrigger/AlwaysUnbuffered on Master Local - Master Trigger (UnityEngine.GameObject) for Largo: S: "StartTest" I: 0 F: 0 B: False (non-local non-master non-owner)
2022.02.05 21:23:37 Log        -  [Behaviour] Custom:StartTest won't, disabled
2022.02.05 21:23:37 Log        -  [Behaviour] Will execute ActivateCustomTrigger/AlwaysUnbuffered on Master Local - Master Trigger (UnityEngine.GameObject) for kaylen17: S: "StartTest" I: 0 F: 0 B: False (non-local non-master non-owner)
2022.02.05 21:23:37 Log        -  [Behaviour] Custom:StartTest won't, disabled
2022.02.05 21:23:38 Log        -  [Behaviour] Will execute ActivateCustomTrigger/AlwaysUnbuffered on Master Local - Master Trigger (UnityEngine.GameObject) for Castiello: S: "StartTest" I: 0 F: 0 B: False (non-local non-master non-owner)
2022.02.05 21:23:38 Log        -  [Behaviour] Custom:StartTest won't, disabled
2022.02.05 21:23:39 Log        -  [Behaviour] Will execute ActivateCustomTrigger/AlwaysUnbuffered on Master Local - Master Trigger (UnityEngine.GameObject) for Potbottom: S: "StartTest" I: 0 F: 0 B: False (non-local non-master non-owner)
2022.02.05 21:23:39 Log        -  [Behaviour] Custom:StartTest won't, disabled
2022.02.05 21:23:42 Log        -  [Behaviour] OnPlayerEnteredRoom
2022.02.05 21:23:42 Log        -  Voice DeliveryMode: UnreliableUnsequenced
2022.02.05 21:23:42 Log        -  [Behaviour] OnPlayerJoined Altul
2022.02.05 21:23:42 Log        -  [Network Processing] Sending transfer of ownership of 100001 to 1.
```

**Comment by Natsumi-sama** [comment]
Ah thanks there we go actually fixed now, must have been a merge conflict.
